package com.example.springboot;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@RestController
@CrossOrigin(origins = "http://localhost:4200")
@Controller // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private RecipeRepository recipeRepository;

    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addNewRecipe (@RequestParam String title
            , @RequestParam String description, @RequestParam String type, @RequestParam Integer preptime, @RequestParam Integer cookingtime
        , @RequestParam String content) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request

        Recipe recipe = new Recipe();
        recipe.setTitle(title);
        recipe.setDescription(description);
        recipe.setType(type);
        recipe.setPreparationtime(preptime);
        recipe.setCookingtimeime(cookingtime);
        recipe.setContent(content);
        recipeRepository.save(recipe);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Recipe> getAllUsers() {
        // This returns a JSON or XML with the users
        return recipeRepository.findAll();
    }
}